// Generated by CoffeeScript 1.7.1
(function() {
  var outputError, runApplescript, spark, spawn;

  spark = require('spark');

  spawn = require('child_process').spawn;

  outputError = function(err) {
    if (!err) {
      return;
    }
    console.error("An error occurred:");
    return console.dir(err);
  };

  runApplescript = function(script) {
    var as;
    as = spawn("osascript", ["-ss"]);
    as.stdin.write(script);
    return as.stdin.end();
  };

  spark.on('login', function() {
    return spark.listDevices().then(function(devices) {
      var core;
      core = devices[0];
      return spark.getEventStream('release', 'mine', function(data) {
        var keys, pin, script;
        data = data.replace(/^[^\{]*(\{.*\})[^\}]*$/, "$1");
        try {
          data = JSON.parse(data);
          pin = data.data;
          console.log("Pushed " + pin);
          keys = {
            D1: "key code 126",
            D2: "key code 124",
            D3: "key code 125",
            D4: "key code 123",
            ALL: "key code 48 using command down"
          };
          script = "tell application \"System Events\"\n  " + keys[pin] + "\nend tell";
          return runApplescript(script);
        } catch (_error) {}
      });
    });
  });

  spark.login({
    username: process.env.SPARK_USERNAME,
    password: process.env.SPARK_PASSWORD
  });

}).call(this);
